<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="AdminHome.aspx.cs" Inherits="Golddigger.Admin.AdminHome" %>

<asp:Content ID="Content" ContentPlaceHolderID="MainContent" runat="server">
    <asp:UpdatePanel runat="server" ID="UpdateGridPanel">
        <ContentTemplate>
            <div class="row">
                <div class="well">
                    <asp:GridView ID="GridViewUsers" runat="server"
                        SelectMethod="GridViewUsers_GetData"
                        UpdateMethod="GridViewUsers_UpdateItem"
                        DeleteMethod="GridViewUsers_DeleteItem"
                        ItemType="Golddigger.Models.User"
                        AllowPaging="True"
                        PageSize="5"
                        AllowSorting="True"
                        DataKeyNames="Id"
                        AutoGenerateEditButton="true"
                        AutoGenerateDeleteButton="true"
                        AutoGenerateColumns="false"
                        CssClass="table table-responsive">
                        <Columns>
                            <asp:BoundField DataField="UserName" HeaderText="UserName" SortExpression="UserName" />
                            <asp:BoundField DataField="IsFemale" HeaderText="IsFemale" SortExpression="IsFemale" />
                            <asp:BoundField DataField="IsDeleted" HeaderText="IsDeleted" SortExpression="IsDeleted" />
                            <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                        </Columns>
                    </asp:GridView>
                </div>
            </div>
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>
